name: Interchain Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - frag/foundation
permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        id: build_push_image
        uses: docker/build-push-action@v3
        with:
          file: ictest.Dockerfile
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            core:local
  test-terra-start:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true

      - name: checkout code
        uses: actions/checkout@v4

      - run: make ictest-start

  test-ibc-transfer:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true

      - name: checkout code
        uses: actions/checkout@v4

      - run: make ictest-ibc

  test-ibc-hooks:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true

      - name: checkout code
        uses: actions/checkout@v4

      - run: make ictest-ibc-hooks
    
  test-ibc-pfm:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true

      - name: checkout code
        uses: actions/checkout@v4

      - run: make ictest-ibc-pfm

  test-validator:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true

      - name: checkout code
        uses: actions/checkout@v4

      - run: make ictest-validator
